# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PHOTONAI test and test deploy

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  pytest:
    name: Run PHOTONAI tests and publish test coverage
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.6
      - name: Install dependencies
        run: |
          pip install wheel flake8
          python setup.py egg_info
          pip install pytest pytest-cov coveralls -r photonai_neuro.egg-info/requires.txt
      - name: Test with pytest
        run: |
          PYTHONPATH=./ pytest ./test --cov=./photonai_neuro --tb=long
#      - name: Coveralls
#        run: coveralls
#        env:
#          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
